/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './message.component.ngfactory';
import * as import2 from './message.component';
import * as import3 from './message.service';
import * as import4 from '@angular/common';
import * as import5 from './message-list.component';
const styles_MessageListComponent:any[] = ([] as any[]);
export const RenderType_MessageListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MessageListComponent,
  data: {}
}
);
function View_MessageListComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-message',([] as any[]),(null as any),(null as any),(null as any),import1.View_MessageComponent_0,import1.RenderType_MessageComponent)),
      import0.ɵdid(49152,(null as any),0,import2.MessageComponent,[import3.MessageService],{message: [
        0,
        'message'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n            ']))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  },(null as any));
}
export function View_MessageListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-8 col-md-offset-2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_MessageListComponent_1)),
    import0.ɵdid(802816,(null as any),0,import4.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    var co:import5.MessageListComponent = v.component;
    const currVal_0:any = co.messages;
    ck(v,4,0,currVal_0);
  },(null as any));
}
function View_MessageListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),(null as any),View_MessageListComponent_0,RenderType_MessageListComponent)),
    import0.ɵdid(114688,(null as any),0,import5.MessageListComponent,[import3.MessageService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const MessageListComponentNgFactory:import0.ComponentFactory<import5.MessageListComponent> = import0.ɵccf('app-message-list',import5.MessageListComponent,View_MessageListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvQ3Vyc29zL1VkZW15IC0gQW5ndWxhciAmIE5vZGUvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZS1saXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9DdXJzb3MvVWRlbXkgLSBBbmd1bGFyICYgTm9kZS9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLWxpc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovUHJvamVjdHMvQ3Vyc29zL1VkZW15IC0gQW5ndWxhciAmIE5vZGUvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZS1saXN0LmNvbXBvbmVudC50cy5NZXNzYWdlTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvQ3Vyc29zL1VkZW15IC0gQW5ndWxhciAmIE5vZGUvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZS1saXN0LmNvbXBvbmVudC50cy5NZXNzYWdlTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgICAgICAgICA8YXBwLW1lc3NhZ2VcbiAgICAgICAgICAgICAgICAgICAgW2lucHV0TWVzc2FnZV09XCJtZXNzYWdlXCJcbiAgICAgICAgICAgICAgICAgICAgKm5nRm9yPVwibGV0IG1lc3NhZ2Ugb2YgbWVzc2FnZXNcIj5cbiAgICAgICAgICAgIDwvYXBwLW1lc3NhZ2U+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtbWVzc2FnZS1saXN0PjwvYXBwLW1lc3NhZ2UtbGlzdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0VZO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFFeUM7OztJQURqQztJQURSLFNBQ1EsU0FEUjs7Ozs7SUFGWjtNQUNRO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBc0M7SUFDbEM7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFHYztJQUNaOzs7O0lBRk07SUFGUixTQUVRLFNBRlI7Ozs7O0lDRlo7Z0JBQUE7OztJQUFBOzs7In0=
